@SmartTaskOrchestrator_HostAddress = http://localhost:5000

# POST {{SmartTaskOrchestrator_HostAddress}}/tasks
# Accept: application/json
# Content-Type: application/json

GET {{SmartTaskOrchestrator_HostAddress}}/swagger
Accept: application/json
Content-Type: application/json

